name: Auto Push and Release (Magento-Payment)

on:
  push:
    branches:
      - magento-payment  # Trigger workflow only when this branch is updated

jobs:
  update-main:
    name: Sync Magento-Payment to Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge changes into main
        run: |
          git checkout main
          git merge --no-ff magento-payment -m "Automated merge from magento-payment to main"
          git push origin main

  release:
    name: Create Release
    needs: update-main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version number
        id: get_version
        run: |
          VERSION=$(date +'%Y.%m.%d-%H%M%S')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: "Automated release from GitHub Actions"
          draft: false
          prerelease: false
